---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels: 
    app.kubernetes.io/instance: chatbot-oct9-pr-patch-2
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: chatbot-oct9-pr-patch-2 
  name: chatbot-oct9-pr-patch-2
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi